"""initial

Revision ID: 46ea370bd99
Revises: None
Create Date: 2016-11-17 16:27:10.505299

"""

# revision identifiers, used by Alembic.
revision = '46ea370bd99'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Country', sa.Column('is_g20', sa.Boolean(), nullable=True))
    op.add_column('Country', sa.Column('is_oecd', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Country', 'is_oecd')
    op.drop_column('Country', 'is_g20')
    ### end Alembic commands ###
